//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class M03_RoleService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M03_RoleService()
        {
            this.M03_RoleServiceEmployee = new HashSet<M03_RoleServiceEmployee>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> role_id { get; set; }
        public Nullable<System.Guid> service_id { get; set; }
        public Nullable<int> access_level { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.Guid> tenant_id { get; set; }
    
        public virtual M03_Role M03_Role { get; set; }
        public virtual M03_Service M03_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M03_RoleServiceEmployee> M03_RoleServiceEmployee { get; set; }
    }
}
