//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class M03_RoleServiceEmployee
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> roleservice_id { get; set; }
        public Nullable<System.Guid> employee_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modify_time { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.Guid> tenant_id { get; set; }
    
        public virtual M03_Employee M03_Employee { get; set; }
        public virtual M03_RoleService M03_RoleService { get; set; }
    }
}
